src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MovieRepository::class)
 */
class Movie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $year;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $direction;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $scenario;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $genres;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $releases;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageUrl;

    /**
     * @ORM\OneToMany(targetEntity=MovieVote::class, mappedBy="movie", orphanRemoval=true)
     */
    private $movieVotes;

    public function __construct()
    {
        $this->movieVotes = new ArrayCollection();
    }

    private const DEFAULT_IMAGE_URL = "images/defaultPoster.jpg";

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getDirection(): ?string
    {
        return $this->direction;
    }

    public function setDirection(?string $direction): self
    {
        $this->direction = $direction;

        return $this;
    }

    public function getScenario(): ?string
    {
        return $this->scenario;
    }

    public function setScenario(?string $scenario): self
    {
        $this->scenario = $scenario;

        return $this;
    }

    public function getGenres(): ?string
    {
        return $this->genres;
    }

    public function setGenres(?string $genres): self
    {
        $this->genres = $genres;

        return $this;
    }

    public function getReleases(): ?string
    {
        return $this->releases;
    }

    public function setReleases(?string $releases): self
    {
        $this->releases = $releases;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return strlen($this->imageUrl) > 0 ? $this->imageUrl : self::DEFAULT_IMAGE_URL;
    }

    public function setImageUrl(string $imageUrl): self
    {
        $this->imageUrl = $imageUrl;

        return $this;
    }

    public function getDirectionArray(): ?array {
        $result = explode(",",$this->direction);
        return $result;
    }

    public function getScenarioArray(): ?array {
        $result = explode(",",$this->scenario);
        return $result;
    }

    public function getGenresArray(): ?array {
        $result = explode(",",$this->genres);
        return $result;
    }

    public function getReleasesArray(): ?array {
        $result = [];
        $arr = explode(",",$this->releases);
        foreach($arr as $key => $row) {
            $rowArr = explode(":",$row);
            $result[$rowArr[0]] = $rowArr[1];
        }
        return $result;
    }

    /**
     * @return Collection|MovieVote[]
     */
    public function getMovieVotes(): Collection
    {
        return $this->movieVotes;
    }

    public function addMovieVote(MovieVote $movieVote): self
    {
        if (!$this->movieVotes->contains($movieVote)) {
            $this->movieVotes[] = $movieVote;
            $movieVote->setMovie($this);
        }

        return $this;
    }

    public function removeMovieVote(MovieVote $movieVote): self
    {
        if ($this->movieVotes->removeElement($movieVote)) {
            // set the owning side to null (unless already changed)
            if ($movieVote->getMovie() === $this) {
                $movieVote->setMovie(null);
            }
        }

        return $this;
    }
}

src/Controller/MovixController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Collections\Criteria;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

use App\Entity\Movie;
use App\Entity\MovieVote;
use App\Service\MovieService;
use App\Model\ErrorStatus;

class MovixController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        return $this->render('movix/index.html.twig', [
            'controller_name' => 'MovixController',
        ]);
    }

    /**
     * @Route("/getMovies/{page}", defaults={"page"=1}, name="getMovies")
     */
    public function getMovies(Request $request, EntityManagerInterface $em, int $page): Response {
        $page   = $page < 1 ? 1 : $page;
        $limit  = 5;
        $offset = ($page-1) * $limit;
        $count  = $em->getRepository(Movie::class)->createQueryBuilder('m')
            ->select('count(m.id)')->getQuery()->getSingleScalarResult();
        $pages  = ceil($count / $limit);
        $criteria = Criteria::create()
            ->setMaxResults($limit)
            ->setFirstResult($offset);
        $movies = $em->getRepository(Movie::class)
            ->matching($criteria)->toArray();

        return $this->render('movix/movies/getMovies.html.twig', [
            'controller_name' => 'MovixController',
            'movies' => $movies,
            'page' => $page,
            'pages' => $pages,
        ]);
    }

    /**
     * @Route("/addMovie", name="addMovie", defaults={"id"=null})
     * @Route("/editMovie/{id}", name="editMovie")
     */
    public function addMovie(Request $request, MovieService $service, EntityManagerInterface $em, ?int $id): Response {
        $movie = null;
        $errorStatus = new ErrorStatus();
        if($id !== null) $movie = $this->getDoctrine()
            ->getRepository(Movie::class)
            ->find($id);
        if(!$movie) {
            $movie = new Movie();
        }

        if($request->getMethod() == 'POST') {
            $movie
                ->setTitle($request->get('movie_title'))
                ->setYear($request->get('movie_year'))
                ->setDirection($request->get('movie_direction'))
                ->setScenario($request->get('movie_scenario'))
                ->setGenres($request->get('movie_genres'))
                ->setReleases($request->get('movie_releases'))
                ->setImageUrl($request->get('movie_imageUrl'));
            ;

            $errorStatus = $service->validateMovie($movie);

            if(!$errorStatus->hasErrors()) {
                $em->persist($movie);
                $em->flush();
                return $this->redirectToRoute('getMovies', ['page' => 1]);
            }
        }

        return $this->render('movix/movies/addMovie.html.twig', [
            'controller_name' => 'MovixController',
            'movie' => $movie,
            'errorStatus' => $errorStatus,
        ]);
    }

    /**
     * @Route("/removeMovie/{id}", name="removeMovie")
     */
    public function removeMovie(int $id): Response {
        return $this->render('movix/movies/removeMovie.html.twig', [
            'controller_name' => 'MovixController',
        ]);
    }

    /**
     * @Route("/voteMovie/{id}/{point}", name="voteMovie")
     */
    public function voteMovie(int $id, int $point, EntityManagerInterface $em, Security $security) {
        $point = $point <= -1 ? -1 : ($point >= 1 ? 1 : 0); 
        $user = $security->getUser();
        if($id !== null) $movie = $this->getDoctrine()
            ->getRepository(Movie::class)
            ->find($id);
        if($movie && $user) {
            $movieVote = $em->getRepository(MovieVote::class)
                ->findOneBy(['user'=>$user->getId(),'movie'=>$movie->getId()]);
            if(!$movieVote) {
                $movieVote = new MovieVote();
            }
            $movieVote->setUser($user);
            $movieVote->setMovie($movie);
            $movieVote->setPoint($point);
            $em->persist($movieVote);
            $em->flush();
        }
        return $this->redirectToRoute('getMovies', ['page' => 1]);
    }
}

templates/movix/movies/addMovie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movies{% endblock %}

{% block body %}

<form class="container" method="post">

    <div class="row">
        <div class="col">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col">
            {% if movie.id|default(null) == null %}
                <h1>Add Movie</h1>
            {% else %}
                <h1>Edit Movie</h1>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr/>
        </div>
    </div>
    {# FORM BEGIN #}
    {# FIELD BEGIN #}
    <div class="row form-group">
        {% set isError = false %}
        {% set errors = errorStatus.findObjectFieldErrors('movie','title') %}
        {% if errors|length > 0 %}
            {% set isError = true %}
        {% endif %}
        <div class="col text-right col-sm-2">
            <label for="movie.title">Title</label>
        </div>
        <div class="col">
            <input type="text" class="form-control {%if isError %}is-invalid{%endif%}" id="movie.title" name="movie.title" value="{{movie.title|default('')}}" placeholder="Enter Title" />
            {% for error in errors %}
                <div class="invalid-feedback">
                    {{error.message}}
                </div>
            {% endfor %}
        </div>
    </div>
    {# FIELD END #}
    {# FIELD BEGIN #}
    <div class="row form-group">
        {% set isError = false %}
        {% set errors = errorStatus.findObjectFieldErrors('movie','year') %}
        {% if errors|length > 0 %}
            {% set isError = true %}
        {% endif %}
        <div class="col text-right col-sm-2">
            <label for="movie.year">Year</label>
        </div>
        <div class="col">
            <input type="number" class="form-control {%if isError %}is-invalid{%endif%}" id="movie.year" name="movie.year" value="{{movie.year|default('')}}" placeholder="Enter Year" />
            {% for error in errors %}
                <div class="invalid-feedback">
                    {{error.message}}
                </div>
            {% endfor %}
        </div>
    </div>
    {# FIELD END #}
    {# FIELD BEGIN #}
    <div class="form-group">
        {% set isError = false %}
        {% set errors = errorStatus.findObjectFieldErrors('movie','direction') %}
        {% if errors|length > 0 %}
            {% set isError = true %}
        {% endif %}
        <div class="row">
            <div class="col text-right col-sm-2">
                <label for="movie.direction">Direction</label>
            </div>
            <div class="col">
                <input type="text" class="form-control {%if isError %}is-invalid{%endif%}" id="movie.direction" name="movie.direction" value="{{movie.direction|default('')}}" placeholder="Enter Direction" aria-describedby="movie.direction.help"/>
                {% for error in errors %}
                    <div class="invalid-feedback">
                        {{error.message}}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col col-sm-2"></div>
            <div class="col">
                <small id="movie.direction.help" class="form-text text-muted"> Format: who, who, ... </small>
            </div>
        </div>
    </div>
    {# FIELD END #}
    {# FIELD BEGIN #}
    <div class="form-group">
        {% set isError = false %}
        {% set errors = errorStatus.findObjectFieldErrors('movie','scenario') %}
        {% if errors|length > 0 %}
            {% set isError = true %}
        {% endif %}
        <div class="row">
            <div class="col text-right col-sm-2">
                <label for="movie.scenario">Scenario</label>
            </div>
            <div class="col">
                <input type="text" class="form-control {%if isError %}is-invalid{%endif%}" id="movie.scenario" name="movie.scenario" value="{{movie.scenario|default('')}}" placeholder="Enter Scenario" aria-describedby="movie.scenario.help"/>
                {% for error in errors %}
                    <div class="invalid-feedback">
                        {{error.message}}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col col-sm-2"></div>
            <div class="col">
                <small id="movie.scenario.help" class="form-text text-muted"> Format: who, who, ... </small>
            </div>
        </div>
    </div>
    {# FIELD END #}
    {# FIELD BEGIN #}
    <div class="form-group">
        {% set isError = false %}
        {% set errors = errorStatus.findObjectFieldErrors('movie','genres') %}
        {% if errors|length > 0 %}
            {% set isError = true %}
        {% endif %}
        <div class="row">
            <div class="col text-right col-sm-2">
                <label for="movie.genres">Genres</label>
            </div>
            <div class="col">
                <input type="text" class="form-control {%if isError %}is-invalid{%endif%}" id="movie.genres" name="movie.genres" value="{{movie.genres|default('')}}" placeholder="Enter Genres" aria-describedby="movie.genres.help"/>
                {% for error in errors %}
                    <div class="invalid-feedback">
                        {{error.message}}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col col-sm-2"></div>
            <div class="col">
                <small id="movie.genres.help" class="form-text text-muted"> Format: what, what, ... </small>
            </div>
        </div>
    </div>
    {# FIELD END #}
    {# FIELD BEGIN #}
    <div class="form-group">
        {% set isError = false %}
        {% set errors = errorStatus.findObjectFieldErrors('movie','releases') %}
        {% if errors|length > 0 %}
            {% set isError = true %}
        {% endif %}
        <div class="row">
            <div class="col text-right col-sm-2">
                <label for="movie.releases">Releases</label>
            </div>
            <div class="col">
                <input type="text" class="form-control {%if isError %}is-invalid{%endif%}" id="movie.releases" name="movie.releases" value="{{movie.releases|default('')}}" placeholder="Enter Releases" aria-describedby="movie.releases.help"/>
                {% for error in errors %}
                    <div class="invalid-feedback">
                        {{error.message}}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col col-sm-2"></div>
            <div class="col">
                <small id="movie.releases.help" class="form-text text-muted"> Format: where:when, where:when, ... </small>
            </div>
        </div>
    </div>
    {# FIELD END #}
    {# FIELD BEGIN #}
    <div class="row form-group">
        {% set isError = false %}
        {% set errors = errorStatus.findObjectFieldErrors('movie','imageUrl') %}
        {% if errors|length > 0 %}
            {% set isError = true %}
        {% endif %}
        <div class="col text-right col-sm-2">
            <label for="movie.imageUrl">Image Url</label>
        </div>
        <div class="col">
            <input type="text" class="form-control {%if isError %}is-invalid{%endif%}" id="movie.imageUrl" name="movie.imageUrl" value="{{movie.imageUrl|default('')}}" placeholder="Enter Image Url" />
            {% for error in errors %}
                <div class="invalid-feedback">
                    {{error.message}}
                </div>
            {% endfor %}
        </div>
    </div>
    {# FIELD END #}
    {# BUTTONS BEGIN #}
    <div class="row">
        <div class="col">
            <hr/>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-success">
                {% if movie.id|default(null) == null %}
                    Add
                {% else %}
                    Edit
                {% endif %}
            </button>
            <a class="btn btn-primary" href="{{path('getMovies')}}">Cancel</a>
        </div>
    </div>
    <input type="hidden" id="movie.id" name="movie.id" value="{{movie.id|default('')}}"/>
    {# BUTTONS END #}
    {# FORM END #}
</form>
{% endblock %}

templates/movix/movies/getMovies.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movies{% endblock %}

{% block body %}

<div class="container">

    <div class="row">
        <div class="col">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col">
            <h1>Movies</h1>
        </div>
        <div class="col">
            
            {# Paginator Begin #}
            {% set pagePrev = page <= 1 ? 1 : page - 1 %}
            {% set pageNext = page >= pages ? pages : page + 1 %}
              <ul class="pagination">
                {% if app.user %}
                    <a class="btn btn-success" href="{{path('addMovie')}}">Add</a>
                {% endif %}
                &nbsp;
                <li class="page-item {%if page==pagePrev%}disabled{%endif%}">
                  <a class="page-link" href="{{path('getMovies',{page:pagePrev})}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Prev ({{pagePrev}})</span>
                  </a>
                </li>
                {% for iPage in range(1,pages) %}
                    {% if iPage == 1 or iPage == pages or (iPage >= page-1 and iPage <= page+2 ) %}
                        <li class="page-item {%if iPage==page%}active{%endif%}"><a class="page-link" href="{{path('getMovies',{page:iPage})}}">{{iPage}}</a></li>
                    {% endif %}
                {% endfor %}
                <li class="page-item {%if page==pageNext%}disabled{%endif%}">
                  <a class="page-link" href="{{path('getMovies',{page:pageNext})}}" aria-label="Next">
                    <span class="sr-only">Next ({{pageNext}})</span>
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
              </ul>
            {# Paginator End#}

        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr/>
        </div>
    </div>
    {% for movie in movies %}
        <div class="row">
            <div class="col">
                <h2>{{movie.title}}</h2>
            </div>
            <div class="col">
                {% if app.user %}
                    {% set editMovieUrl = path('editMovie',{id:movie.id}) %}
                    {% set removeMovieUrl = path('removeMovie',{id:movie.id}) %}
                    {% set voteMovieLikeUrl = path('voteMovie',{id:movie.id,point:1}) %}
                    {% set voteMovieDunnoUrl = path('voteMovie',{id:movie.id,point:0}) %}
                    {% set voteMovieDislikeUrl = path('voteMovie',{id:movie.id,point:-1}) %}
                    <a class="btn btn-primary" href="{{editMovieUrl}}">Edit</a>
                    <button class="btn btn-danger" onclick="confirmRemove('{{movie.title}}','{{movie.id}}','{{removeMovieUrl}}')">Remove</button>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <img class="img-movie-poster" src="{{asset(movie.imageUrl)}}"/>
            </div>
            <div class="col">
                {# FIELD BEGIN #}
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">Id</div>
                            <div class="col">{{movie.id}}</div>
                        </div>
                    </div>
                </div>
                {# FIELD END #}
                {# FIELD BEGIN #}
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">Year</div>
                            <div class="col">{{movie.year}}</div>
                        </div>
                    </div>
                </div>
                {# FIELD END #}
                {# FIELD BEGIN #}
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">Direction</div>
                            <div class="col">{{movie.directionArray|join(', ')}}</div>
                        </div>
                    </div>
                </div>
                {# FIELD END #}
                {# FIELD BEGIN #}
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">Scenario</div>
                            <div class="col">{{movie.scenarioArray|join(', ')}}</div>
                        </div>
                    </div>
                </div>
                {# FIELD END #}
                {# FIELD BEGIN #}
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">Genres</div>
                            <div class="col">{{movie.genresArray|join(', ')}}</div>
                        </div>
                    </div>
                </div>
                {# FIELD END #}
                {# FIELD BEGIN #}
                {% for key, release in movie.releasesArray %} 
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="col">Release ({{key}})</div>
                                <div class="col">{{release}}</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {# FIELD END #}
                {# FIELD BEGIN #}
                {% if app.user %}
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">Points (Votes)</div>
                            <div class="col">
                                {% set points = 0 %}
                                {% set myPoint = 0 %}
                                {% for vote in movie.movieVotes %}
                                    {% set points = points + vote.point %}
                                    {% if vote.user.id == app.user.id %}
                                        {% set myPoint = vote.point %}
                                    {% endif %}
                                {% endfor %}
                                {{points}} ({{movie.movieVotes|length}})
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {# FIELD END #}
                {# FIELD BEGIN #}
                {% if app.user %}
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <a class="btn {%if myPoint==1%}btn-success{%else%}btn-secondary{%endif%} btn-sm" href="{{voteMovieLikeUrl}}";>Like</a>
                                <a class="btn {%if myPoint==0%}btn-warning{%else%}btn-secondary{%endif%} btn-sm" href="{{voteMovieDunnoUrl}}">Dunno</a>
                                <a class="btn {%if myPoint==-1%}btn-danger{%else%}btn-secondary{%endif%} btn-sm" href="{{voteMovieDislikeUrl}}">Dislike</a> 
                            </div>
                            <div class="col">
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {# FIELD END #}
            </div>
        </div>

        <div class="row">
            <div class="col">
                <hr/><br/>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

{% block javascripts %}
<script>
function confirmRemove(title,id,url) {
    if(confirm('Do you want to remove the "'+title+'" (Id:'+id+') movie?')) {
        window.location = url;
    }
}
</script>
{% endblock javascripts %}

{% block stylesheets %}
<style>
.img-movie-poster {
    border: 1px solid rgba(0,0,0,0.1);
    box-shadow: 4px 4px 5px -3px rgba(0,0,0,0.5);
    width: 140px;
    height: auto;
}
</style>
{% endblock stylesheets %}